### ISSUE TITLE
Some part of captions are missing on the left side navigation menu.

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm/st2docs#1080]
On the left side navigation menu, Some part of captions (e.g. `Getting Started`) are missing as below.
<img width="877" alt="スクリーンショット 2021-07-24 10 02 09" src="https://user-images.githubusercontent.com/469934/126855934-fe5b9f09-2fe5-40c7-8e96-1943176be370.png">

**Comment by amanda11** [comment]
Confirmed that it's an issue. Can't see any changes to the index.rst that would have affected this, not sure if its a change in the generator (e.g. newer version). But none of the ":catpion" lines are coming out on the left-hand menu.

**Comment by winem** [comment]
Actually they aren't missing, they are just very good in hiding. You see them if you mark the left column. So this may be due to a new generator or something similiar as @amanda11 mentioned that they are rendered in a different color now. 

![Selection_269](https://user-images.githubusercontent.com/1457899/126881538-e3e37adc-d2d4-4354-bb81-eb6bbb4f20ce.png)
![Selection_271](https://user-images.githubusercontent.com/1457899/126881534-60abb30b-52a5-4dae-a734-5490e9501a57.png)

**Comment by winem** [comment]
I investigated this a bit more and could see that up to 3.4 `.wy-menu-vertical header, .wy-menu-vertical p.caption` defined the style: 

![Selection_273](https://user-images.githubusercontent.com/1457899/126883879-3f1dd813-a162-46cd-aca0-c74c4f41519d.png)

At some point this style was no longer referenced / used. With 3.5: 
![Selection_272](https://user-images.githubusercontent.com/1457899/126883887-9dc89cd6-9301-40ce-a08c-768752337b77.png)

Unfortunately I could not reproduce the issue with `make docker-run` which is probably due to some caching. 

Hope this helps someone with more experience in frontend development or gives anyone a hint. 

I also checked that the requirements on sphinx did not change between the docs for 3.4 and 3.5.
