### ISSUE TITLE
Docs on accessing key value items from sensors and actions need better doc

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2docs#156]
Should we fix this doc to talk about the DatastoreService methods instead? https://docs.stackstorm.com/datastore.html#storing-and-retrieving-from-python-client

**Comment by Kami** [comment]
I think you are confusing two different things again - Python client library (st2client) and datastore service which is available to sensors and actions via {sensor,action}_service.

The documentation you linked to talks about Python client library (st2client) and CLI so docs about datastore service have nothing to do with that.

We already have docs on sensor_service and action_service which which talk how to access datastore via those services (those docs are in the actions and sensors section of the documentation) - https://docs.stackstorm.com/actions.html#action-service, https://docs.stackstorm.com/sensors.html#datastore-management-operations

**Comment by lakshmi-kannan** [comment]
>The documentation you linked to talks about Python client library (st2client) and CLI so docs about datastore service have nothing to do with that.

I think we have to deprecate this option since we now expose sensor_service and action_service. That's my real question.

**Comment by Kami** [comment]
I think we are still having a misunderstanding.

Python client library doesn't really have anything to do with sensor and action services (besides action and service sensor utilizing it). It's two different levels of abstraction serving different purposes.

As far as documentation goes - I'm all for improving it, but as noted above - we already have docs on action and sensor service and we still need docs for client library since that's unrelated to action and sensor service (I'm of course not against improving the existing docs and adding more documentation though).
