### ISSUE TITLE
Document pre-canned parameters for runner types

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2docs#402]
In the docs, it's not obvious which default parameters come with each runner type. I opened this issue: https://github.com/StackStorm/st2/issues/3251 before I knew the `hosts` argument was built in to the `run-remote-script` runner, and I was beating my head on the desk for a while wondering why stackstorm was complaining about me not providing a parameter that wasn't defined in the action metadata.

I only found this out by finding another example - the docs should definitely be clearer here.

**Comment by jasoanderson** [comment]
I want to reiterate this. I ran into this same issue last Friday, the documentation wasn't clear what was considered base parameters. I was working creating an action of type remote command line. I kept getting a mapping issue, because I was trying to specify that the host parameter was needed. I was able to get help through slack on this issue, but after rereading the documentation, I believe the documentation needs to be made more clear on what parameters are always there, and what are additional ones we can add. Maybe even with an example.

**Comment by LindsayHill** [comment]
Can you create a PR with the sort of example you want to see in the docs?

This page: https://docs.stackstorm.com/reference/runners.html should have all the parameters for runners. Are there some missing from there, or do you want this information included/linked from elsewhere in the docs?

Which section of the docs do you want to see updated?

**Comment by blag** [comment]
The `timeout` parameter is not listed on [the Actions page](https://docs.stackstorm.com/actions.html#action-runners).

There is a link to the Runners section of the Reference page, but it's buried in the middle of a lot of text.

At the very least we should make sure to list _all_ runner parameters in the action runners section of the actions page.
