### ISSUE TITLE
mistral database is referred to in upgrade guide but its not present with 3.2dev on centos 8

### ISSUE THREAD

**Issue by amanda11** [StackStorm/st2docs#977]
On https://docs.stackstorm.com/latest/install/upgrades.html it states for upgrade:

3. Upgrade Mistral database:

/opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf upgrade head
/opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf populate | grep -v -e openstack -e keystone -e ironicclient

On stackstorm 3.2 dev on Centos 8 with python 3 there is no /opt/stackstorm/mistral to update.

As I understand it mistral is not installed for python3. 

Does this just require a note to say unless upgrading from 3.2 and higher on python 3? Is there anything special to do though when upgrading from 3.1 to 3.2?

Also in step 2 it states to upgrade the st2mistral package, but that is not present on Centos8/python3.

**Comment by armab** [comment]
Thanks for the fixes!

As we're deprecating Mistral (https://github.com/StackStorm/st2/issues/4762), new OS platforms that were added recently (`Ubuntu18` and `EL8`) come with Orquesta only as a workflow engine.

Instead of adding a special case for each U18/EL8, I would prefer a warning stating that if their OS doesn't have Mistral installed they can skip mistral packages and migration step.

Mistral is going to be fully removed from StackStorm `v3.3` and so having smaller diff would make more sense when we're looking forward to deprecating it.

**Comment by amanda11** [comment]
@armab thanks for the feedback, have revised the documentation change with notes rather than calling out EL8 explicitly..

**Comment by armab** [comment]
Closed via https://github.com/StackStorm/st2docs/pull/978
